# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-angellist` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-angellist`.


module RuboCop; end
module RuboCop::Angellist; end

class RuboCop::Angellist::Plugin < ::LintRoller::Plugin
  sig { returns(::LintRoller::About) }
  def about; end

  sig { params(_context: ::LintRoller::Context).returns(::LintRoller::Rules) }
  def rules(_context); end

  sig { params(context: ::LintRoller::Context).returns(T::Boolean) }
  def supported?(context); end
end

RuboCop::Angellist::VERSION = T.let(T.unsafe(nil), String)
module RuboCop::Cop; end
module RuboCop::Cop::Angellist; end

class RuboCop::Cop::Angellist::ClassStructure < ::RuboCop::Cop::Layout::ClassStructure
  sig { params(class_node: ::RuboCop::AST::ClassNode).void }
  def on_class(class_node); end

  private

  sig { params(elements: T::Array[::RuboCop::AST::Node]).void }
  def check_class_methods_vs_graphql_fields(elements); end

  sig { params(elements: T::Array[::RuboCop::AST::Node]).void }
  def check_class_methods_vs_instance_methods(elements); end

  sig { params(elements: T::Array[::RuboCop::AST::Node]).void }
  def check_graphql_object_type_vs_constants(elements); end

  sig { params(elements: T::Array[::RuboCop::AST::Node]).void }
  def check_graphql_ordering(elements); end

  sig { params(elements: T::Array[::RuboCop::AST::Node]).void }
  def check_nested_classes_vs_class_methods(elements); end

  sig { params(class_node: ::RuboCop::AST::ClassNode).void }
  def check_strict_ordering(class_node); end

  sig do
    params(
      class_node: T.any(::RuboCop::AST::ClassNode, ::RuboCop::AST::SelfClassNode)
    ).returns(T::Array[::RuboCop::AST::Node])
  end
  def class_elements(class_node); end

  sig { params(node: ::RuboCop::AST::Node).returns(T::Boolean) }
  def class_method?(node); end

  sig { params(node: ::RuboCop::AST::Node).returns(T::Boolean) }
  def constant?(node); end

  sig { params(node: ::RuboCop::AST::Node).returns(T::Boolean) }
  def graphql_field?(node); end

  sig { params(node: ::RuboCop::AST::Node).returns(T::Boolean) }
  def graphql_object_type?(node); end

  sig { params(node: ::RuboCop::AST::Node).returns(T::Boolean) }
  def instance_method?(node); end

  sig { params(node: ::RuboCop::AST::Node).returns(T::Boolean) }
  def nested_class?(node); end
end

RuboCop::Cop::Angellist::ClassStructure::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Angellist::EnforceMethodCallSites < ::RuboCop::Cop::Base
  sig { params(config: ::RuboCop::Config, options: T::Hash[::Symbol, T.untyped]).void }
  def initialize(config = T.unsafe(nil), options = T.unsafe(nil)); end

  sig { params(node: ::RuboCop::AST::SendNode).void }
  def on_csend(node); end

  sig { params(node: ::RuboCop::AST::Node).void }
  def on_ivasgn(node); end

  sig { params(node: ::RuboCop::AST::Node).void }
  def on_lvasgn(node); end

  sig { params(node: ::RuboCop::AST::SendNode).void }
  def on_send(node); end

  private

  sig { params(restriction: T::Hash[::String, T.untyped]).returns(T::Boolean) }
  def allowed_call_site?(restriction); end

  sig { params(node: ::RuboCop::AST::SendNode, restriction: T::Hash[::String, T.untyped]).returns(::String) }
  def build_message(node, restriction); end

  sig { params(node: ::RuboCop::AST::SendNode).void }
  def check_dynamic_send(node); end

  sig { params(node: ::RuboCop::AST::SendNode).void }
  def check_method_call(node); end

  sig { params(node: ::RuboCop::AST::SendNode).void }
  def check_method_reference(node); end

  sig { params(node: T.nilable(::RuboCop::AST::Node)).returns(T.nilable(::String)) }
  def extract_const_name(node); end

  sig { params(node: ::RuboCop::AST::SendNode, restriction: T::Hash[::String, T.untyped]).returns(T::Boolean) }
  def matches_restriction?(node, restriction); end

  sig { params(module_name: T.nilable(T.any(::String, ::Symbol))).returns(::String) }
  def normalize_module_name(module_name); end

  sig { params(methods: T.untyped).returns(T::Array[::Symbol]) }
  def parse_methods(methods); end

  sig { params(receiver: T.nilable(::RuboCop::AST::Node)).returns(T.nilable(::String)) }
  def resolve_receiver_module(receiver); end

  sig { returns(T::Array[T::Hash[::String, T.untyped]]) }
  def restrictions; end
end

class RuboCop::Cop::Angellist::ForbidInstanceVariableGetSet < ::RuboCop::Cop::Base
  def on_send(node); end
end

RuboCop::Cop::Angellist::ForbidInstanceVariableGetSet::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Angellist::ForbidInstanceVariableGetSet::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Angellist::GraphqlExplicitMethod < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Angellist::GraphqlFieldHelpers
  extend ::RuboCop::Cop::AutoCorrector

  def field_name(param0 = T.unsafe(nil)); end
  def has_camelize_false?(param0 = T.unsafe(nil)); end
  def has_method_option?(param0 = T.unsafe(nil)); end
  def has_resolver_or_mutation?(param0 = T.unsafe(nil)); end
  def on_send(node); end
end

RuboCop::Cop::Angellist::GraphqlExplicitMethod::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Angellist::GraphqlExplicitMethod::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Angellist::GraphqlExplicitObject < ::RuboCop::Cop::Base
  def graphql_class?(param0 = T.unsafe(nil)); end
  def has_field_call?(param0 = T.unsafe(nil)); end
  def has_object_type_call?(param0 = T.unsafe(nil)); end
  def on_class(node); end

  private

  def exempt_class_name?(node); end
end

RuboCop::Cop::Angellist::GraphqlExplicitObject::MSG = T.let(T.unsafe(nil), String)

module RuboCop::Cop::Angellist::GraphqlFieldHelpers
  private

  def class_defines_method?(class_node, method_name); end
  def find_hash_arg(node); end
  def insert_method_option(corrector, node, option_key, method_name); end
  def resolver_method_needed?(node, method_name); end
  def underscore(str); end
end

class RuboCop::Cop::Angellist::GraphqlFieldNameCamelized < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Angellist::GraphqlFieldHelpers
  extend ::RuboCop::Cop::AutoCorrector

  def field_name(param0 = T.unsafe(nil)); end
  def has_camelize_false?(param0 = T.unsafe(nil)); end
  def has_method_or_resolver_method?(param0 = T.unsafe(nil)); end
  def has_resolver_or_mutation?(param0 = T.unsafe(nil)); end
  def on_send(node); end

  private

  def camelize(str); end
end

RuboCop::Cop::Angellist::GraphqlFieldNameCamelized::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Angellist::GraphqlFieldNameCamelized::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Angellist::GraphqlResolverMethod < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Angellist::GraphqlFieldHelpers
  extend ::RuboCop::Cop::AutoCorrector

  def field_with_method_option(param0 = T.unsafe(nil)); end
  def on_send(node); end

  private

  def find_method_pair(field_node); end
end

RuboCop::Cop::Angellist::GraphqlResolverMethod::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Angellist::GraphqlResolverMethod::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Angellist::NoUnless < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  sig { params(node: ::RuboCop::AST::IfNode).void }
  def on_if(node); end

  private

  sig { params(corrector: ::RuboCop::Cop::Corrector, node: ::RuboCop::AST::Node).void }
  def autocorrect(corrector, node); end

  sig { params(corrector: ::RuboCop::Cop::Corrector, node: ::RuboCop::AST::SendNode).void }
  def autocorrect_send_node(corrector, node); end

  sig { returns(T::Hash[::Symbol, ::Symbol]) }
  def inverse_comparisons; end
end

RuboCop::Cop::Angellist::NoUnless::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Angellist::PreferDateCurrent < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  sig { params(node: ::RuboCop::AST::Node).void }
  def on_send(node); end

  def time_zone_today?(param0 = T.unsafe(nil)); end

  private

  sig { params(corrector: ::RuboCop::Cop::Corrector, node: ::RuboCop::AST::Node).void }
  def autocorrect(corrector, node); end
end

RuboCop::Cop::Angellist::PreferDateCurrent::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Angellist::PreferDateCurrent::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Angellist::RedundantExtendTSig < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  extend ::RuboCop::Cop::AutoCorrector

  def extend_t_sig?(param0 = T.unsafe(nil)); end

  sig { params(node: ::RuboCop::AST::SendNode).void }
  def on_send(node); end
end

RuboCop::Cop::Angellist::RedundantExtendTSig::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Angellist::RedundantExtendTSig::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Angellist::TimecopWithoutBlock < ::RuboCop::Cop::Base
  sig { params(node: ::RuboCop::AST::Node).void }
  def on_send(node); end

  def timecop_call?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Angellist::TimecopWithoutBlock::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Angellist::TimecopWithoutBlock::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)
