# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-sorbet` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-sorbet`.


module RuboCop; end
module RuboCop::Cop; end
module RuboCop::Cop::Sorbet; end

class RuboCop::Cop::Sorbet::AllowIncompatibleOverride < ::RuboCop::Cop::Base
  def on_block(node); end
  def on_numblock(node); end
  def on_send(node); end
  def override?(param0 = T.unsafe(nil)); end
  def sig?(param0); end
  def sig_dot_override?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::AllowIncompatibleOverride::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::AllowIncompatibleOverride::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::BindingConstantWithoutTypeAlias < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  def on_casgn(node); end
  def requires_type_alias?(param0 = T.unsafe(nil)); end
  def type_alias_with_block?(param0 = T.unsafe(nil)); end
  def type_alias_without_block(param0 = T.unsafe(nil)); end

  private

  def send_leaf(node); end
end

RuboCop::Cop::Sorbet::BindingConstantWithoutTypeAlias::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::BindingConstantWithoutTypeAlias::WITHOUT_BLOCK_MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::BlockMethodDefinition < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Alignment
  extend ::RuboCop::Cop::AutoCorrector

  def activesupport_concern_class_methods_block?(param0 = T.unsafe(nil)); end
  def module_extends_activesupport_concern?(param0 = T.unsafe(nil)); end
  def on_block(node); end
  def on_numblock(node); end

  private

  def adjust_for_closing_parenthesis(end_pos); end
  def autocorrect_method_in_block(corrector, node); end
  def closing_parenthesis_follows(source); end
  def find_end_position_with_arguments(node); end
  def find_end_position_without_arguments(node); end
  def find_method_signature_end_position(node); end
  def handle_method_without_body(node, indent); end
  def handle_multiline_method_without_body(node); end
  def handle_single_line_method(node, indent); end
  def in_activesupport_concern_class_methods_block?(node); end
  def single_line_method?(node); end
  def transform_args_to_block_args(node); end
end

RuboCop::Cop::Sorbet::BlockMethodDefinition::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::BuggyObsoleteStrictMemoization < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::MatchRange
  include ::RuboCop::Cop::Alignment
  include ::RuboCop::Cop::LineLengthHelp
  include ::RuboCop::Cop::Sorbet::TargetSorbetVersion
  extend ::RuboCop::Cop::AutoCorrector
  extend ::RuboCop::Cop::Sorbet::TargetSorbetVersion::ClassMethods

  def buggy_legacy_memoization_pattern?(param0 = T.unsafe(nil)); end
  def on_begin(node); end
  def relevant_file?(file); end
end

RuboCop::Cop::Sorbet::BuggyObsoleteStrictMemoization::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::CallbackConditionalsBinding < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Alignment
  extend ::RuboCop::Cop::AutoCorrector

  def argumentless_unbound_callable_callback_conditional?(param0 = T.unsafe(nil)); end
  def on_send(node); end

  private

  def immediately_enclosing_module_name(node); end
end

RuboCop::Cop::Sorbet::CallbackConditionalsBinding::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::CallbackConditionalsBinding::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::CapitalizedTypeParameters < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sorbet::SignatureHelp
  extend ::RuboCop::Cop::AutoCorrector

  def on_csend(node); end
  def on_send(node); end
  def on_signature(node); end
  def t_type_parameter?(param0 = T.unsafe(nil)); end
  def type_parameters?(param0 = T.unsafe(nil)); end

  private

  def check_type_parameters_case(node); end
end

RuboCop::Cop::Sorbet::CapitalizedTypeParameters::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::CapitalizedTypeParameters::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::CheckedTrueInSignature < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::Sorbet::SignatureHelp

  def offending_node(param0); end
  def on_signature(node); end
end

RuboCop::Cop::Sorbet::CheckedTrueInSignature::MESSAGE = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::ConstantsFromStrings < ::RuboCop::Cop::Base
  def on_csend(node); end
  def on_send(node); end
end

RuboCop::Cop::Sorbet::ConstantsFromStrings::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ConstantsFromStrings::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::EmptyLineAfterSig < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::Sorbet::SignatureHelp
  extend ::RuboCop::Cop::AutoCorrector

  def on_signature(sig); end
  def sig_or_signable_method_definition?(param0 = T.unsafe(nil)); end

  private

  def contains_only_rubocop_directives?(range); end
  def lines_between(node1, node2, buffer: T.unsafe(nil)); end
  def next_sibling(node); end
end

RuboCop::Cop::Sorbet::EmptyLineAfterSig::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::EnforceSigilOrder < ::RuboCop::Cop::Sorbet::ValidSigil
  include ::RuboCop::Cop::RangeHelp

  def on_new_investigation; end

  protected

  def autocorrect(corrector); end
  def check_magic_comments_order(tokens); end
  def extract_magic_comments(processed_source); end
end

RuboCop::Cop::Sorbet::EnforceSigilOrder::CODING_REGEX = T.let(T.unsafe(nil), Regexp)
RuboCop::Cop::Sorbet::EnforceSigilOrder::FROZEN_REGEX = T.let(T.unsafe(nil), Regexp)
RuboCop::Cop::Sorbet::EnforceSigilOrder::INDENT_REGEX = T.let(T.unsafe(nil), Regexp)
RuboCop::Cop::Sorbet::EnforceSigilOrder::MAGIC_REGEX = T.let(T.unsafe(nil), Regexp)
RuboCop::Cop::Sorbet::EnforceSigilOrder::PREFERRED_ORDER = T.let(T.unsafe(nil), Hash)

class RuboCop::Cop::Sorbet::EnforceSignatures < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sorbet::SignatureHelp
  extend ::RuboCop::Cop::AutoCorrector

  def accessor?(param0 = T.unsafe(nil)); end
  def on_def(node); end
  def on_defs(node); end
  def on_new_investigation; end
  def on_send(node); end
  def on_signature(node); end
  def scope(node); end

  private

  def add_accessor_parameter_if_needed(suggest, symbol, method); end
  def allow_rbs?; end
  def autocorrect_with_signature_type(corrector, node, type); end
  def check_node(node); end
  def create_signature_suggestion(node, type); end
  def param_type_placeholder; end
  def populate_accessor_suggestion(suggest, node); end
  def populate_method_definition_suggestion(suggest, node); end
  def populate_signature_suggestion(suggest, node); end
  def rbs_checker; end
  def return_type_placeholder; end
  def set_void_return_for_writer(suggest, method); end
  def sig_checker; end
  def signature_style; end
  def writer_or_accessor?(method); end
end

class RuboCop::Cop::Sorbet::EnforceSignatures::RBSSignatureChecker < ::RuboCop::Cop::Sorbet::EnforceSignatures::SignatureChecker
  def signature_node(node); end

  private

  def find_non_send_ancestor(node); end
end

RuboCop::Cop::Sorbet::EnforceSignatures::RBSSignatureChecker::RBS_COMMENT_REGEX = T.let(T.unsafe(nil), Regexp)

class RuboCop::Cop::Sorbet::EnforceSignatures::RBSSuggestion
  def initialize(indent); end

  def has_block; end
  def has_block=(_arg0); end
  def params; end
  def params=(_arg0); end
  def returns; end
  def returns=(_arg0); end
  def to_autocorrect; end

  private

  def generate_signature; end
end

class RuboCop::Cop::Sorbet::EnforceSignatures::SigSignatureChecker < ::RuboCop::Cop::Sorbet::EnforceSignatures::SignatureChecker
  def initialize(processed_source); end

  def clear_signature(scope); end
  def on_signature(node, scope); end
  def signature_node(scope); end
end

class RuboCop::Cop::Sorbet::EnforceSignatures::SigSuggestion
  def initialize(indent, param_placeholder, return_placeholder); end

  def params; end
  def params=(_arg0); end
  def returns; end
  def returns=(_arg0); end
  def to_autocorrect; end

  private

  def generate_params; end
  def generate_return; end
end

class RuboCop::Cop::Sorbet::EnforceSignatures::SignatureChecker
  def initialize(processed_source); end

  protected

  def preceding_comments(node); end
  def processed_source; end
end

RuboCop::Cop::Sorbet::EnforceSignatures::VALID_STYLES = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::EnforceSingleSigil < ::RuboCop::Cop::Sorbet::ValidSigil
  include ::RuboCop::Cop::RangeHelp

  def on_new_investigation; end

  protected

  def autocorrect(corrector); end
  def extract_all_sigils(processed_source); end
end

class RuboCop::Cop::Sorbet::FalseSigil < ::RuboCop::Cop::Sorbet::HasSigil
  def minimum_strictness; end
end

class RuboCop::Cop::Sorbet::ForbidComparableTEnum < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sorbet::TEnum

  def mix_in_comparable?(param0 = T.unsafe(nil)); end
  def on_send(node); end
end

RuboCop::Cop::Sorbet::ForbidComparableTEnum::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidComparableTEnum::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidExtendTSigHelpersInShims < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  extend ::RuboCop::Cop::AutoCorrector

  def extend_t_sig_or_helpers?(param0 = T.unsafe(nil)); end
  def on_send(node); end
end

RuboCop::Cop::Sorbet::ForbidExtendTSigHelpersInShims::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidExtendTSigHelpersInShims::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidIncludeConstLiteral < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  def dynamic_inclusion?(param0 = T.unsafe(nil)); end
  def on_send(node); end

  private

  def neither_const_nor_self?(node); end
  def within_onymous_module?(node); end
end

RuboCop::Cop::Sorbet::ForbidIncludeConstLiteral::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidIncludeConstLiteral::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidMixesInClassMethods < ::RuboCop::Cop::Base
  def mixes_in_class_methods?(param0 = T.unsafe(nil)); end
  def on_csend(node); end
  def on_send(node); end
end

RuboCop::Cop::Sorbet::ForbidMixesInClassMethods::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidMixesInClassMethods::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidRBIOutsideOfAllowedPaths < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp

  def on_new_investigation; end

  private

  def allowed_paths; end
end

class RuboCop::Cop::Sorbet::ForbidSig < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sorbet::SignatureHelp

  def on_signature(node); end
end

RuboCop::Cop::Sorbet::ForbidSig::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::ForbidSigWithRuntime < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sorbet::SignatureHelp

  def on_signature(node); end
end

RuboCop::Cop::Sorbet::ForbidSigWithRuntime::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::ForbidSigWithoutRuntime < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sorbet::SignatureHelp
  extend ::RuboCop::Cop::AutoCorrector

  def on_signature(node); end
end

RuboCop::Cop::Sorbet::ForbidSigWithoutRuntime::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::ForbidSuperclassConstLiteral < ::RuboCop::Cop::Base
  def dynamic_superclass?(param0 = T.unsafe(nil)); end
  def on_class(node); end
end

RuboCop::Cop::Sorbet::ForbidSuperclassConstLiteral::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::ForbidTAbsurd < ::RuboCop::Cop::Base
  def on_csend(node); end
  def on_send(node); end
  def t_absurd?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::ForbidTAbsurd::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidTAbsurd::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidTAnyWithNil < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  def nil_const_node?(param0 = T.unsafe(nil)); end
  def on_csend(node); end
  def on_send(node); end
  def t_any_call?(param0 = T.unsafe(nil)); end

  private

  def build_replacement(non_nil_args); end
end

RuboCop::Cop::Sorbet::ForbidTAnyWithNil::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidTAnyWithNil::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidTBind < ::RuboCop::Cop::Base
  def on_csend(node); end
  def on_send(node); end
  def t_bind?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::ForbidTBind::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidTBind::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidTCast < ::RuboCop::Cop::Base
  def on_csend(node); end
  def on_send(node); end
  def t_cast?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::ForbidTCast::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidTCast::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidTEnum < ::RuboCop::Cop::Base
  def on_class(node); end
  def t_enum?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::ForbidTEnum::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::ForbidTHelpers < ::RuboCop::Cop::Base
  def on_csend(node); end
  def on_send(node); end
  def t_helpers?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::ForbidTHelpers::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidTHelpers::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidTLet < ::RuboCop::Cop::Base
  def on_csend(node); end
  def on_send(node); end
  def t_let?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::ForbidTLet::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidTLet::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidTMust < ::RuboCop::Cop::Base
  def on_csend(node); end
  def on_send(node); end
  def t_must?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::ForbidTMust::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidTMust::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidTSig < ::RuboCop::Cop::Base
  def on_csend(node); end
  def on_send(node); end
  def t_sig?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::ForbidTSig::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidTSig::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidTStruct < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Alignment
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::CommentsHelp
  extend ::RuboCop::Cop::AutoCorrector

  def on_class(node); end
  def on_send(node); end
  def t_props?(param0 = T.unsafe(nil)); end
  def t_struct?(param0 = T.unsafe(nil)); end

  private

  def initialize_method(indent, props); end
  def previous_line_blank?(node); end
end

RuboCop::Cop::Sorbet::ForbidTStruct::MSG_PROPS = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidTStruct::MSG_STRUCT = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::ForbidTStruct::Property
  def initialize(node, kind, name, type, default:, factory:); end

  def attr_accessor; end
  def attr_sig; end
  def default; end
  def factory; end
  def initialize_assign; end
  def initialize_param; end
  def initialize_sig_param; end
  def kind; end
  def name; end
  def nilable?; end
  def node; end
  def type; end
end

RuboCop::Cop::Sorbet::ForbidTStruct::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidTStruct::TStructWalker
  include ::RuboCop::AST::Traversal
  extend ::RuboCop::AST::NodePattern::Macros

  def initialize; end

  def extend_t_sig?(param0 = T.unsafe(nil)); end
  def has_extend_t_sig; end
  def on_send(node); end
  def props; end
  def t_struct_prop?(param0 = T.unsafe(nil)); end
end

class RuboCop::Cop::Sorbet::ForbidTTypeAlias < ::RuboCop::Cop::Base
  def on_block(node); end
  def on_numblock(node); end
  def t_type_alias?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::ForbidTTypeAlias::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::ForbidTUnsafe < ::RuboCop::Cop::Base
  def on_csend(node); end
  def on_send(node); end
  def t_unsafe?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::ForbidTUnsafe::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidTUnsafe::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidTUntyped < ::RuboCop::Cop::Base
  def on_send(node); end
  def t_untyped?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::ForbidTUntyped::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ForbidTUntyped::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ForbidTypeAliasedShapes < ::RuboCop::Cop::Base
  def on_block(node); end
  def on_numblock(node); end
  def shape_type_alias?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::ForbidTypeAliasedShapes::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::ForbidUntypedStructProps < ::RuboCop::Cop::Base
  def on_class(node); end
  def subclass_of_t_struct?(param0 = T.unsafe(nil)); end
  def t_nilable_untyped(param0 = T.unsafe(nil)); end
  def t_struct(param0 = T.unsafe(nil)); end
  def t_untyped(param0 = T.unsafe(nil)); end
  def untyped_props(param0); end
end

RuboCop::Cop::Sorbet::ForbidUntypedStructProps::MSG = T.let(T.unsafe(nil), String)

module RuboCop::Cop::Sorbet::GemVersionAnnotationHelper
  def gem_version_annotations; end

  private

  def gem_version_annotation?(comment); end
  def gem_versions(comment); end
end

RuboCop::Cop::Sorbet::GemVersionAnnotationHelper::VERSION_PREFIX = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::HasSigil < ::RuboCop::Cop::Sorbet::ValidSigil
  def require_sigil_on_all_files?; end
end

class RuboCop::Cop::Sorbet::IgnoreSigil < ::RuboCop::Cop::Sorbet::HasSigil
  def minimum_strictness; end
end

class RuboCop::Cop::Sorbet::ImplicitConversionMethod < ::RuboCop::Cop::Base
  def on_alias(node); end
  def on_def(node); end
  def on_defs(node); end
  def on_send(node); end
end

RuboCop::Cop::Sorbet::ImplicitConversionMethod::IMPLICIT_CONVERSION_METHODS = T.let(T.unsafe(nil), Array)
RuboCop::Cop::Sorbet::ImplicitConversionMethod::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ImplicitConversionMethod::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::KeywordArgumentOrdering < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sorbet::SignatureHelp

  def on_signature(node); end

  private

  def check_order_for_kwoptargs(parameters); end
end

class RuboCop::Cop::Sorbet::MultipleTEnumValues < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sorbet::TEnum

  def enums_block?(param0 = T.unsafe(nil)); end
  def on_block(node); end
  def on_class(node); end
end

RuboCop::Cop::Sorbet::MultipleTEnumValues::MSG = T.let(T.unsafe(nil), String)

module RuboCop::Cop::Sorbet::MutableConstantSorbetAwareBehaviour
  def on_assignment(value); end

  class << self
    def prepended(base); end
  end
end

class RuboCop::Cop::Sorbet::ObsoleteStrictMemoization < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::MatchRange
  include ::RuboCop::Cop::Alignment
  include ::RuboCop::Cop::LineLengthHelp
  include ::RuboCop::Cop::Sorbet::TargetSorbetVersion
  extend ::RuboCop::Cop::AutoCorrector
  extend ::RuboCop::Cop::Sorbet::TargetSorbetVersion::ClassMethods

  def legacy_memoization_pattern?(param0 = T.unsafe(nil)); end
  def on_begin(node); end
  def relevant_file?(file); end
end

RuboCop::Cop::Sorbet::ObsoleteStrictMemoization::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::RedundantExtendTSig < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  extend ::RuboCop::Cop::AutoCorrector

  def extend_t_sig?(param0 = T.unsafe(nil)); end
  def on_send(node); end
end

RuboCop::Cop::Sorbet::RedundantExtendTSig::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::RedundantExtendTSig::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::Refinement < ::RuboCop::Cop::Base
  def on_send(node); end
end

RuboCop::Cop::Sorbet::Refinement::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::Refinement::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::RuntimeOnFailureDependsOnChecked < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sorbet::SignatureHelp

  def checked_tests_or_always?(param0 = T.unsafe(nil)); end
  def on_failure_call?(param0 = T.unsafe(nil)); end
  def on_signature(node); end
end

RuboCop::Cop::Sorbet::RuntimeOnFailureDependsOnChecked::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::SelectByIsA < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  def on_csend(node); end
  def on_send(node); end
  def type_narrowing_select?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::SelectByIsA::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::SelectByIsA::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::SignatureBuildOrder < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sorbet::SignatureHelp
  extend ::RuboCop::Cop::AutoCorrector

  def on_signature(node); end
  def root_call(param0); end

  private

  def builder_method_indexes; end
  def call_chain(node); end
  def expected_source(expected_calls_and_indexes); end
end

module RuboCop::Cop::Sorbet::SignatureHelp
  extend ::RuboCop::AST::NodePattern::Macros

  def bare_sig?(param0 = T.unsafe(nil)); end
  def on_block(node); end
  def on_numblock(node); end
  def on_signature(_node); end
  def sig_with_runtime?(param0 = T.unsafe(nil)); end
  def sig_without_runtime?(param0 = T.unsafe(nil)); end
  def signature?(param0 = T.unsafe(nil)); end
end

class RuboCop::Cop::Sorbet::SingleLineRbiClassModuleDefinitions < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  def on_class(node); end
  def on_module(node); end

  private

  def convert_newlines_to_semicolons(source); end
end

RuboCop::Cop::Sorbet::SingleLineRbiClassModuleDefinitions::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::StrictSigil < ::RuboCop::Cop::Sorbet::HasSigil
  def minimum_strictness; end
end

class RuboCop::Cop::Sorbet::StrongSigil < ::RuboCop::Cop::Sorbet::HasSigil
  def minimum_strictness; end
end

module RuboCop::Cop::Sorbet::TEnum
  extend ::RuboCop::AST::NodePattern::Macros

  def initialize(*_arg0); end

  def after_class(node); end
  def on_class(node); end
  def t_enum?(param0 = T.unsafe(nil)); end

  private

  def in_t_enum_class?; end
end

module RuboCop::Cop::Sorbet::TargetSorbetVersion
  mixes_in_class_methods ::RuboCop::Cop::Sorbet::TargetSorbetVersion::ClassMethods

  def enabled_for_sorbet_static_version?; end
  def read_sorbet_static_version_from_bundler_lock_file; end
  def sorbet_enabled?; end
  def target_sorbet_static_version_from_bundler_lock_file; end

  class << self
    def included(target); end
  end
end

module RuboCop::Cop::Sorbet::TargetSorbetVersion::ClassMethods
  def minimum_target_sorbet_static_version(version); end
  def supports_target_sorbet_static_version?(version); end
end

class RuboCop::Cop::Sorbet::TrueSigil < ::RuboCop::Cop::Sorbet::HasSigil
  def minimum_strictness; end
end

class RuboCop::Cop::Sorbet::TypeAliasName < ::RuboCop::Cop::Base
  def on_casgn(node); end
  def underscored_type_alias?(param0 = T.unsafe(nil)); end
end

RuboCop::Cop::Sorbet::TypeAliasName::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::Sorbet::ValidGemVersionAnnotations < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sorbet::GemVersionAnnotationHelper

  def on_new_investigation; end

  private

  def valid_version?(version_string); end
end

RuboCop::Cop::Sorbet::ValidGemVersionAnnotations::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ValidGemVersionAnnotations::VALID_OPERATORS = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::ValidSigil < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  def on_new_investigation; end

  protected

  def autocorrect(corrector); end
  def check_double_commented_sigil(sigil, strictness); end
  def check_sigil_present(sigil); end
  def check_strictness_level(sigil, strictness); end
  def check_strictness_not_empty(sigil, strictness); end
  def check_strictness_valid(sigil, strictness); end
  def exact_strictness; end
  def extract_sigil(processed_source); end
  def extract_strictness(sigil); end
  def minimum_strictness; end
  def require_sigil_on_all_files?; end
  def suggested_strictness; end
  def suggested_strictness_level; end
end

RuboCop::Cop::Sorbet::ValidSigil::INVALID_SIGIL_MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::Sorbet::ValidSigil::SIGIL_REGEX = T.let(T.unsafe(nil), Regexp)
RuboCop::Cop::Sorbet::ValidSigil::STRICTNESS_LEVELS = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::Sorbet::VoidCheckedTests < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::Cop::Sorbet::SignatureHelp
  extend ::RuboCop::Cop::AutoCorrector

  def checked_tests(param0); end
  def on_signature(node); end

  private

  def top_level_void(node); end
end

RuboCop::Cop::Sorbet::VoidCheckedTests::MESSAGE = T.let(T.unsafe(nil), String)
module RuboCop::Cop::Style; end

class RuboCop::Cop::Style::MutableConstant < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::Sorbet::MutableConstantSorbetAwareBehaviour
end

module RuboCop::Sorbet; end
class RuboCop::Sorbet::Error < ::StandardError; end

class RuboCop::Sorbet::Plugin < ::LintRoller::Plugin
  def about; end
  def rules(_context); end
  def supported?(context); end
end

RuboCop::Sorbet::VERSION = T.let(T.unsafe(nil), String)
