# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-thread_safety` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-thread_safety`.


module RuboCop; end
module RuboCop::Cop; end

module RuboCop::Cop::OperationWithThreadsafeResult
  extend ::RuboCop::AST::NodePattern::Macros

  def operation_produces_threadsafe_object?(param0 = T.unsafe(nil)); end
end

module RuboCop::Cop::ThreadSafety; end

class RuboCop::Cop::ThreadSafety::ClassAndModuleAttributes < ::RuboCop::Cop::Base
  def attr?(param0 = T.unsafe(nil)); end
  def attr_internal?(param0 = T.unsafe(nil)); end
  def class_attr?(param0 = T.unsafe(nil)); end
  def mattr?(param0 = T.unsafe(nil)); end
  def on_send(node); end

  private

  def class_attribute_allowed?; end
  def defined_in_singleton_class?(node); end
  def singleton_attr?(node); end
end

RuboCop::Cop::ThreadSafety::ClassAndModuleAttributes::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::ThreadSafety::ClassAndModuleAttributes::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::ThreadSafety::ClassInstanceVariable < ::RuboCop::Cop::Base
  def class_eval_scope?(param0 = T.unsafe(nil)); end
  def class_methods_module?(param0 = T.unsafe(nil)); end
  def instance_variable_get_call?(param0 = T.unsafe(nil)); end
  def instance_variable_set_call?(param0 = T.unsafe(nil)); end
  def module_function_for?(param0 = T.unsafe(nil), param1); end
  def new_lexical_scope?(param0 = T.unsafe(nil)); end
  def on_ivar(node); end
  def on_ivasgn(node); end
  def on_send(node); end

  private

  def class_method_definition?(node); end
  def in_class_eval?(node); end
  def in_def_class_methods?(node); end
  def in_def_class_methods_dsl?(node); end
  def in_def_class_methods_module?(node); end
  def in_def_module_function?(node); end
  def in_def_sclass?(node); end
  def in_defs?(node); end
  def instance_variable_call?(node); end
  def match_name?(arg_name, method_name); end
  def method_definition?(node); end
  def module_function_bare_access_modifier?(node); end
  def singleton_method_definition?(node); end
  def synchronized?(node); end
end

RuboCop::Cop::ThreadSafety::ClassInstanceVariable::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::ThreadSafety::ClassInstanceVariable::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::ThreadSafety::DirChdir < ::RuboCop::Cop::Base
  def chdir?(param0 = T.unsafe(nil)); end
  def on_csend(node); end
  def on_send(node); end

  private

  def allow_call_with_block?; end
end

RuboCop::Cop::ThreadSafety::DirChdir::MESSAGE = T.let(T.unsafe(nil), String)
RuboCop::Cop::ThreadSafety::DirChdir::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::ThreadSafety::MutableClassInstanceVariable < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::FrozenStringLiteral
  include ::RuboCop::Cop::ConfigurableEnforcedStyle
  include ::RuboCop::Cop::OperationWithThreadsafeResult
  extend ::RuboCop::Cop::AutoCorrector

  def autocorrect(corrector, node); end
  def define_method?(param0 = T.unsafe(nil)); end
  def define_singleton_method?(param0 = T.unsafe(nil)); end
  def on_ivasgn(node); end
  def on_masgn(node); end
  def on_or_asgn(node); end
  def operation_produces_immutable_object?(param0 = T.unsafe(nil)); end
  def range_enclosed_in_parentheses?(param0 = T.unsafe(nil)); end
  def splat_value(param0 = T.unsafe(nil)); end

  private

  def check(value); end
  def container?(node); end
  def correct_splat_expansion(corrector, expr, splat_value); end
  def frozen_string_literal?(node); end
  def immutable_literal?(node); end
  def in_class?(node); end
  def mutable_literal?(node); end
  def on_assignment(value); end
  def range_type?(node); end
  def requires_parentheses?(node); end
  def strict_check(value); end
end

RuboCop::Cop::ThreadSafety::MutableClassInstanceVariable::FROZEN_STRING_LITERAL_TYPES_RUBY27 = T.let(T.unsafe(nil), Array)
RuboCop::Cop::ThreadSafety::MutableClassInstanceVariable::FROZEN_STRING_LITERAL_TYPES_RUBY30 = T.let(T.unsafe(nil), Array)
RuboCop::Cop::ThreadSafety::MutableClassInstanceVariable::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::ThreadSafety::NewThread < ::RuboCop::Cop::Base
  def new_thread?(param0 = T.unsafe(nil)); end
  def on_csend(node); end
  def on_send(node); end
end

RuboCop::Cop::ThreadSafety::NewThread::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::ThreadSafety::NewThread::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::ThreadSafety::RackMiddlewareInstanceVariable < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::AllowedIdentifiers
  include ::RuboCop::Cop::OperationWithThreadsafeResult

  def app_variable(param0); end
  def on_class(node); end
  def on_csend(node); end
  def on_send(node); end
  def rack_middleware_like_class?(param0 = T.unsafe(nil)); end

  private

  def extract_application_variable_from_contructor_method(constructor_method); end
  def extract_safe_variables_from_constructor_method(constructor_method); end
  def find_constructor_method(class_node); end
end

RuboCop::Cop::ThreadSafety::RackMiddlewareInstanceVariable::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::ThreadSafety::RackMiddlewareInstanceVariable::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)
module RuboCop::ThreadSafety; end

class RuboCop::ThreadSafety::Plugin < ::LintRoller::Plugin
  def about; end
  def rules(_context); end
  def supported?(context); end
end

module RuboCop::ThreadSafety::Version; end
RuboCop::ThreadSafety::Version::STRING = T.let(T.unsafe(nil), String)
