# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-graphql` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-graphql`.


module RuboCop; end
module RuboCop::Cop; end
module RuboCop::Cop::GraphQL; end

class RuboCop::Cop::GraphQL::ArgumentDescription < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  def on_send(node); end
end

RuboCop::Cop::GraphQL::ArgumentDescription::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::ArgumentDescription::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::GraphQL::ArgumentName < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  def on_send(node); end
end

RuboCop::Cop::GraphQL::ArgumentName::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::ArgumentName::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::GraphQL::ArgumentUniqueness < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodeUniqueness

  def argument_declarations(param0); end
  def on_class(node); end

  private

  def argument_name(node); end
  def field_name(node); end
  def register_offense(current); end
end

RuboCop::Cop::GraphQL::ArgumentUniqueness::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::GraphQL::ContextWriteInType < ::RuboCop::Cop::Base
  def context_write?(param0 = T.unsafe(nil)); end
  def on_send(node); end
end

RuboCop::Cop::GraphQL::ContextWriteInType::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::ContextWriteInType::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::GraphQL::ExtractInputType < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  def on_class(node); end
end

RuboCop::Cop::GraphQL::ExtractInputType::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::GraphQL::ExtractType < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  def on_class(node); end

  private

  def check_fields_prefixes(body); end
  def fractured(body); end
  def ignored_prefix?(word); end
  def message(prefix, field_names); end
end

RuboCop::Cop::GraphQL::ExtractType::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::GraphQL::FieldDefinitions < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::ConfigurableEnforcedStyle
  include ::RuboCop::Cop::CommentsHelp
  include ::RuboCop::GraphQL::NodePattern
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::GraphQL::Sorbet
  include ::RuboCop::GraphQL::Heredoc
  extend ::RuboCop::Cop::AutoCorrector

  def field_kwargs(param0 = T.unsafe(nil)); end
  def on_class(node); end
  def on_module(node); end
  def on_send(node); end

  private

  def check_grouped_field_declarations(body); end
  def check_resolver_is_defined_after_definition(field); end
  def field_has_no_resolver_method(field); end
  def field_name(node); end
  def fields_with_same_resolver(field, resolver); end
  def group_field_declarations(corrector, node); end
  def indent(node); end
  def insert_new_resolver(corrector, field_definition, resolver_definition); end
  def multiple_definitions(field); end
  def offense_message(single_field_using_resolver); end
  def place_resolver_after_field_definition(corrector, node); end
  def remove_old_resolver(corrector, resolver_definition); end
  def resolver_defined_after_definition?(field, method_definition); end
  def signature_to_insert(node); end
end

RuboCop::Cop::GraphQL::FieldDefinitions::GROUP_DEFS_MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::FieldDefinitions::RESOLVER_AFTER_FIELD_MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::FieldDefinitions::RESOLVER_AFTER_LAST_FIELD_MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::FieldDefinitions::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::GraphQL::FieldDescription < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  def on_send(node); end
end

RuboCop::Cop::GraphQL::FieldDescription::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::FieldDescription::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::GraphQL::FieldHashKey < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern
  include ::RuboCop::Cop::RangeHelp
  extend ::RuboCop::Cop::AutoCorrector

  def hash_key_to_use(param0 = T.unsafe(nil)); end
  def on_send(node); end

  private

  def autocorrect(corrector, node); end
  def conflict?(suggested_hash_key_name); end
  def message(hash_key); end
  def resolver_method_definition_for(field); end
end

RuboCop::Cop::GraphQL::FieldHashKey::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::FieldHashKey::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::GraphQL::FieldMethod < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern
  include ::RuboCop::Cop::RangeHelp
  extend ::RuboCop::Cop::AutoCorrector

  def method_to_use(param0 = T.unsafe(nil)); end
  def on_send(node); end

  private

  def autocorrect(corrector, node); end
  def message(method_name); end
  def method_kwarg_set?(field); end
  def suggest_method_name_for(field); end
end

RuboCop::Cop::GraphQL::FieldMethod::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::FieldMethod::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::GraphQL::FieldName < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern
  extend ::RuboCop::Cop::AutoCorrector

  def on_send(node); end

  private

  def rename_field_name(corrector, field, node); end
end

RuboCop::Cop::GraphQL::FieldName::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::FieldName::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::GraphQL::FieldUniqueness < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodeUniqueness

  def false_value?(param0 = T.unsafe(nil)); end
  def field_declarations(param0); end
  def on_class(node); end

  private

  def field_name(node); end
  def register_offense(current); end
end

RuboCop::Cop::GraphQL::FieldUniqueness::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::GraphQL::GraphqlName < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::ConfigurableEnforcedStyle

  def class_name(param0 = T.unsafe(nil)); end
  def graphql_name(param0 = T.unsafe(nil)); end
  def on_class(node); end
end

RuboCop::Cop::GraphQL::GraphqlName::MISSING_NAME = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::GraphqlName::UNNEEDED_OVERRIDE = T.let(T.unsafe(nil), String)

class RuboCop::Cop::GraphQL::LegacyDsl < ::RuboCop::Cop::Base
  def legacy_dsl?(param0 = T.unsafe(nil)); end
  def on_send(node); end
end

RuboCop::Cop::GraphQL::LegacyDsl::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::LegacyDsl::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::GraphQL::MaxComplexitySchema < ::RuboCop::Cop::Base
  def max_complexity(param0 = T.unsafe(nil)); end
  def on_class(node); end
end

RuboCop::Cop::GraphQL::MaxComplexitySchema::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::GraphQL::MaxDepthSchema < ::RuboCop::Cop::Base
  def max_depth(param0 = T.unsafe(nil)); end
  def on_class(node); end
end

RuboCop::Cop::GraphQL::MaxDepthSchema::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::GraphQL::MultipleFieldDefinitions < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::GraphQL::Heredoc
  extend ::RuboCop::Cop::AutoCorrector

  def on_send(node); end

  private

  def field_name(node); end
  def field_sibling_index(field); end
  def group_multiple_definitions(corrector, multiple_definitions); end
  def has_ungrouped_definitions?(multiple_definitions); end
  def insert_new_field(corrector, first, second); end
  def multiple_definitions(field); end
  def remove_old_field(corrector, second); end
end

RuboCop::Cop::GraphQL::MultipleFieldDefinitions::MULTIPLE_DEFINITIONS_MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::MultipleFieldDefinitions::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::GraphQL::NotAuthorizedNodeType < ::RuboCop::Cop::Base
  def has_authorized_method?(param0 = T.unsafe(nil)); end
  def has_can_can_action?(param0 = T.unsafe(nil)); end
  def has_pundit_role?(param0 = T.unsafe(nil)); end
  def implements_node_type?(param0 = T.unsafe(nil)); end
  def on_class(node); end
  def on_module(node); end

  private

  def ignored_class?(klass); end
  def implements_authorization?(node); end
  def possible_parent_classes(node); end
end

RuboCop::Cop::GraphQL::NotAuthorizedNodeType::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::GraphQL::ObjectDescription < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern
  include ::RuboCop::GraphQL::DescriptionMethod

  def interface?(param0 = T.unsafe(nil)); end
  def on_class(node); end
  def on_module(node); end

  private

  def child_nodes(node); end
  def has_description?(node); end
end

RuboCop::Cop::GraphQL::ObjectDescription::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::GraphQL::OrderedArguments < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::GraphQL::SwapRange
  include ::RuboCop::GraphQL::CompareOrder
  extend ::RuboCop::Cop::AutoCorrector

  def argument_declaration(param0); end
  def on_class(node); end

  private

  def argument_declaration_with_block?(node); end
  def argument_name(node); end
  def consecutive_lines(previous, current); end
  def register_offense(previous, current); end
end

RuboCop::Cop::GraphQL::OrderedArguments::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::GraphQL::OrderedFields < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::RangeHelp
  include ::RuboCop::GraphQL::SwapRange
  include ::RuboCop::GraphQL::CompareOrder
  extend ::RuboCop::Cop::AutoCorrector

  def field_declarations(param0); end
  def on_class(node); end
  def on_module(node); end

  private

  def consecutive_fields(previous, current); end
  def field_name(node); end
  def register_offense(previous, current); end
end

RuboCop::Cop::GraphQL::OrderedFields::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::GraphQL::PrepareMethod < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  def graphql_argument_with_prepare_block?(param0 = T.unsafe(nil)); end
  def on_send(node); end
  def prepare_method_string_name?(param0 = T.unsafe(nil)); end
  def prepare_method_symbol_name?(param0 = T.unsafe(nil)); end

  private

  def autocorrect(corrector, node, original_method_name, new_method_name); end
end

RuboCop::Cop::GraphQL::PrepareMethod::ARGUMENT_METHODS = T.let(T.unsafe(nil), Set)
RuboCop::Cop::GraphQL::PrepareMethod::GENERAL_MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::PrepareMethod::PREFER_STRING_MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::PrepareMethod::PREFER_SYMBOL_MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::PrepareMethod::STRING_MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::PrepareMethod::SYMBOL_MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::GraphQL::ResolverMethodLength < ::RuboCop::Cop::Base
  include ::RuboCop::Cop::CodeLength

  def field_definition(param0 = T.unsafe(nil)); end
  def on_def(node); end
  def on_defs(node); end

  private

  def field_is_defined?(node); end
  def message(length); end
end

RuboCop::Cop::GraphQL::ResolverMethodLength::MSG = T.let(T.unsafe(nil), String)

class RuboCop::Cop::GraphQL::UnnecessaryArgumentCamelize < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  def on_send(node); end
end

RuboCop::Cop::GraphQL::UnnecessaryArgumentCamelize::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::UnnecessaryArgumentCamelize::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::GraphQL::UnnecessaryFieldAlias < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern
  extend ::RuboCop::Cop::AutoCorrector

  def on_send(node); end

  private

  def validate_kwargs(field); end
end

RuboCop::Cop::GraphQL::UnnecessaryFieldAlias::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::UnnecessaryFieldAlias::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::GraphQL::UnnecessaryFieldCamelize < ::RuboCop::Cop::Base
  include ::RuboCop::GraphQL::NodePattern

  def on_send(node); end
end

RuboCop::Cop::GraphQL::UnnecessaryFieldCamelize::MSG = T.let(T.unsafe(nil), String)
RuboCop::Cop::GraphQL::UnnecessaryFieldCamelize::RESTRICT_ON_SEND = T.let(T.unsafe(nil), Array)

class RuboCop::Cop::GraphQL::UnusedArgument < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  def argument_declaration?(param0 = T.unsafe(nil)); end
  def on_class(node); end
  def resolve_method_definition(param0); end

  private

  def arg_end(node); end
  def arg_name(declared_arg); end
  def block_or_lambda?(node); end
  def find_declared_arg_nodes(node); end
  def find_resolve_method_node(node); end
  def find_unresolved_args(method_node, declared_arg_nodes); end
  def ignore_arguments_type?(resolve_method_node); end
  def inferred_arg_name(name_as_string); end
  def method_name(node); end
  def register_offense(node, unresolved_args); end
  def scope_changing_syntax?(node); end
  def scoped_node?(node); end
end

RuboCop::Cop::GraphQL::UnusedArgument::MSG = T.let(T.unsafe(nil), String)
module RuboCop::GraphQL; end

class RuboCop::GraphQL::Argument
  extend ::RuboCop::AST::NodePattern::Macros

  def initialize(node); end

  def argument_as(param0 = T.unsafe(nil)); end
  def argument_description(param0 = T.unsafe(nil)); end
  def argument_name(param0 = T.unsafe(nil)); end
  def as; end
  def block; end
  def description; end
  def kwargs; end
  def name; end
  def node; end
end

class RuboCop::GraphQL::Argument::Block
  include ::RuboCop::GraphQL::DescriptionMethod
  extend ::RuboCop::AST::NodePattern::Macros

  def initialize(argument_node); end

  def argument_block(param0 = T.unsafe(nil)); end
  def description; end
end

class RuboCop::GraphQL::Argument::Kwargs
  extend ::RuboCop::AST::NodePattern::Macros

  def initialize(argument_node); end

  def argument_kwargs(param0 = T.unsafe(nil)); end
  def as; end
  def as_kwarg?(param0 = T.unsafe(nil)); end
  def camelize; end
  def camelize_kwarg?(param0 = T.unsafe(nil)); end
  def description; end
  def description_kwarg?(param0 = T.unsafe(nil)); end
  def loads; end
  def loads_kwarg?(param0 = T.unsafe(nil)); end
end

class RuboCop::GraphQL::Class
  def initialize(node); end

  def nested?; end
  def node; end
end

module RuboCop::GraphQL::CompareOrder
  def correct_order?(previous, current); end
  def order_index(field, order); end
end

module RuboCop::GraphQL::DescriptionMethod
  extend ::RuboCop::AST::NodePattern::Macros

  def description_method_call?(param0 = T.unsafe(nil)); end
  def description_with_block_arg?(param0 = T.unsafe(nil)); end
  def find_description_method(nodes); end
end

RuboCop::GraphQL::DescriptionMethod::DESCRIPTION_STRING = T.let(T.unsafe(nil), String)
module RuboCop::GraphQL::Ext; end
module RuboCop::GraphQL::Ext::SnakeCase; end
RuboCop::GraphQL::Ext::SnakeCase::SNAKE_CASE = T.let(T.unsafe(nil), Regexp)

class RuboCop::GraphQL::Field
  extend ::Forwardable
  extend ::RuboCop::AST::NodePattern::Macros

  def initialize(node); end

  def block; end
  def description; end
  def field_description(param0 = T.unsafe(nil)); end
  def field_name(param0 = T.unsafe(nil)); end
  def field_with_body_name(param0 = T.unsafe(nil)); end
  def kwargs; end
  def name; end
  def node; end
  def parent(*args, **_arg1, &block); end
  def resolver_method_name; end
  def schema_member; end
  def sibling_index(*args, **_arg1, &block); end
  def underscore_name; end

  private

  def root_node; end
  def root_node?(node); end
  def root_with_siblings?(node); end
end

class RuboCop::GraphQL::Field::Block
  include ::RuboCop::GraphQL::DescriptionMethod
  extend ::RuboCop::AST::NodePattern::Macros

  def initialize(field_node); end

  def description; end
  def field_block(param0 = T.unsafe(nil)); end
end

RuboCop::GraphQL::Field::CONFLICT_FIELD_NAMES = T.let(T.unsafe(nil), Set)
RuboCop::GraphQL::Field::GRAPHQL_RUBY_KEYWORDS = T.let(T.unsafe(nil), Array)

class RuboCop::GraphQL::Field::Kwargs
  extend ::RuboCop::AST::NodePattern::Macros

  def initialize(field_node); end

  def alias; end
  def alias_kwarg(param0 = T.unsafe(nil)); end
  def camelize; end
  def camelize_kwarg?(param0 = T.unsafe(nil)); end
  def description; end
  def description_kwarg?(param0 = T.unsafe(nil)); end
  def field_kwargs(param0 = T.unsafe(nil)); end
  def hash_key; end
  def hash_key_kwarg?(param0 = T.unsafe(nil)); end
  def method; end
  def method_kwarg?(param0 = T.unsafe(nil)); end
  def resolver; end
  def resolver_kwarg?(param0 = T.unsafe(nil)); end
  def resolver_method_name; end
  def resolver_method_option(param0 = T.unsafe(nil)); end
end

RuboCop::GraphQL::Field::RUBY_KEYWORDS = T.let(T.unsafe(nil), Array)

module RuboCop::GraphQL::Heredoc
  def heredoc?(node); end
  def range_including_heredoc(node); end

  private

  def find_last_heredoc(node); end
end

module RuboCop::GraphQL::NodePattern
  extend ::RuboCop::AST::NodePattern::Macros

  def argument?(param0 = T.unsafe(nil)); end
  def field?(node); end
  def field_definition?(param0 = T.unsafe(nil)); end
  def field_definition_with_body?(param0 = T.unsafe(nil)); end
end

module RuboCop::GraphQL::NodeUniqueness
  def current_class_full_name(node); end
end

class RuboCop::GraphQL::Plugin < ::LintRoller::Plugin
  def about; end
  def rules(_context); end
  def supported?(context); end
end

class RuboCop::GraphQL::SchemaMember
  extend ::RuboCop::AST::NodePattern::Macros

  def initialize(node); end

  def body; end
  def class_contents(param0 = T.unsafe(nil)); end
  def find_method_definition(method_name); end
  def node; end
end

module RuboCop::GraphQL::Sorbet
  extend ::RuboCop::AST::NodePattern::Macros

  def has_sorbet_signature?(node); end
  def sorbet_signature(param0 = T.unsafe(nil)); end
  def sorbet_signature_for(node); end
end

module RuboCop::GraphQL::SwapRange
  include ::RuboCop::Cop::RangeHelp

  def declaration(node); end
  def final_end_location(start_node); end
  def swap_range(corrector, current, previous); end
end

RuboCop::GraphQL::VERSION = T.let(T.unsafe(nil), String)
module UnderscoreString; end
