# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `unicode-display_width` gem.
# Please instead update this file by running `bin/tapioca gem unicode-display_width`.


module Unicode; end

class Unicode::DisplayWidth
  def initialize(ambiguous: T.unsafe(nil), overwrite: T.unsafe(nil), emoji: T.unsafe(nil)); end

  def get_config(**kwargs); end
  def of(string, **kwargs); end

  class << self
    def decompress_index(index, level); end
    def emoji_width(string, mode = T.unsafe(nil), ambiguous = T.unsafe(nil)); end
    def emoji_width_via_possible(string, emoji_set_regex, strict_eaw = T.unsafe(nil), ambiguous = T.unsafe(nil)); end
    def normalize_options(string, ambiguous = T.unsafe(nil), overwrite = T.unsafe(nil), old_options = T.unsafe(nil), **options); end
    def of(string, ambiguous = T.unsafe(nil), overwrite = T.unsafe(nil), old_options = T.unsafe(nil), **options); end
    def width_ascii(string); end
    def width_custom(string, overwrite); end
  end
end

Unicode::DisplayWidth::AMBIGUOUS_MAP = T.let(T.unsafe(nil), Hash)
Unicode::DisplayWidth::ASCII_BACKSPACE = T.let(T.unsafe(nil), String)
Unicode::DisplayWidth::ASCII_NON_ZERO_REGEX = T.let(T.unsafe(nil), Regexp)
Unicode::DisplayWidth::ASCII_NON_ZERO_STRING = T.let(T.unsafe(nil), String)
Unicode::DisplayWidth::DATA_DIRECTORY = T.let(T.unsafe(nil), String)
Unicode::DisplayWidth::DEFAULT_AMBIGUOUS = T.let(T.unsafe(nil), Integer)
Unicode::DisplayWidth::EMOJI_SEQUENCES_REGEX_MAPPING = T.let(T.unsafe(nil), Hash)

module Unicode::DisplayWidth::EmojiSupport
  class << self
    def _recommended; end
    def recommended; end
  end
end

Unicode::DisplayWidth::FIRST_4096 = T.let(T.unsafe(nil), Hash)
Unicode::DisplayWidth::FIRST_AMBIGUOUS = T.let(T.unsafe(nil), Hash)
Unicode::DisplayWidth::INDEX = T.let(T.unsafe(nil), Hash)
Unicode::DisplayWidth::INDEX_FILENAME = T.let(T.unsafe(nil), String)
Unicode::DisplayWidth::INITIAL_DEPTH = T.let(T.unsafe(nil), Integer)
Unicode::DisplayWidth::NOT_COMMON_NARROW_REGEX = T.let(T.unsafe(nil), Hash)
Unicode::DisplayWidth::REGEX_EMOJI_ALL_SEQUENCES = T.let(T.unsafe(nil), Regexp)
Unicode::DisplayWidth::REGEX_EMOJI_ALL_SEQUENCES_AND_VS16 = T.let(T.unsafe(nil), Regexp)
Unicode::DisplayWidth::REGEX_EMOJI_VS16 = T.let(T.unsafe(nil), Regexp)
Unicode::DisplayWidth::UNICODE_VERSION = T.let(T.unsafe(nil), String)
Unicode::DisplayWidth::VERSION = T.let(T.unsafe(nil), String)
