gem:
  # Add your `gem` command parameters here:
  #
  # exclude:
  # - gem_name
  # workers: 5
  doc: false
  loc: false
dsl:
  # Add your `dsl` command parameters here:
  #
  # exclude:
  # - SomeGeneratorName
  # workers: 5
